# Generated by Django 4.0.2 on 2022-05-19 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='nombrePais',
            field=models.CharField(choices=[(1, 'Argentina'), (2, 'Brasil')], max_length=60),
        ),
    ]
