# Generated by Django 4.0.2 on 2022-05-19 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0002_alter_pais_nombrepais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='nombrePais',
            field=models.CharField(max_length=60),
        ),
    ]
