# Generated by Django 4.0.2 on 2022-05-19 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0003_alter_pais_nombrepais'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='fecha',
            field=models.DateField(auto_created=True, default='2022-05-19'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='tipo',
            field=models.CharField(choices=[(1, 'Parcial'), (2, 'Recuperatorio'), (3, 'Globalizador'), (4, 'Final'), (4, 'Otro')], max_length=60),
        ),
        migrations.AlterField(
            model_name='situacion',
            name='detalle',
            field=models.CharField(choices=[(1, 'Titular'), (2, 'Suplente'), (3, 'Provisional')], max_length=60),
        ),
        migrations.DeleteModel(
            name='TipoCalificacion',
        ),
    ]
